config/routes.rb
Rails.application.routes.draw do
  root to: "emploies#index"

  resources :emploies, only: [:index] do
    collection do
      get 'import', to: 'emploies#import'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  validates :external_id, :email, presence: true, uniqueness: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emploies_controller.rb
class EmploiesController < ApplicationController
  def index
    @emploies = Employee.all.decorate
  end

  def import
    ImportEmploiesJob.perform_later

    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/emploies/_employee.html.erb
<div class="employee">
  <h2><%= employee.full_name %></h2>
  <p><strong>Address:</strong> <%= employee.model.address %></p>
  <p><strong>Date of birth:</strong> <%= employee.date_of_birth %></p>
  <p><strong>Email:</strong> <%= employee.model.email %></p>
  <p><strong>Biography:</strong> <%= employee.model.bio %></p>
  <p><strong>Country:</strong> <%= employee.model.country %></p>
  <p><strong>Rating:</strong> <%= employee.model.rating %></p>
</div>

app/views/emploies/index.html.erb
<div>
  <div>
    <%= link_to 'Import list of emploies', import_emploies_path, method: :get %>
    <h1> Emploies </h1>
  </div>
  
  <% @emploies.each do |employee| %>
    <%= render partial: "employee", locals: { employee: employee } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListOfEmployees</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>